### ISSUE TITLE
Python 3.7/windows async training qq

### ISSUE THREAD

**Issue by rbtcollins** [TheCacophonyProject/classifier-pipeline#63]
```
Traceback (most recent call last):
  File "train.py", line 257, in <module>
    main()
  File "train.py", line 252, in main
    train_model(config, "training/" + args.name, **model_args)
  File "train.py", line 130, in train_model
    run_name=rum_name + " " + datetime.datetime.now().strftime("%Y%m%d-%H%M%S"),
  File "C:\Users\robertc\Documents\src\classifier-pipeline\ml_tools\model.py", line 632, in train_model
    self.start_async_load()
  File "C:\Users\robertc\Documents\src\classifier-pipeline\ml_tools\model.py", line 805, in start_async_load
    self.datasets.train.start_async_load(48)
  File "C:\Users\robertc\Documents\src\classifier-pipeline\ml_tools\dataset.py", line 942, in start_async_load
    thread.start()
  File "C:\Users\robertc\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\robertc\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\robertc\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\robertc\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\robertc\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle weakref objects
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\robertc\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\robertc\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Comment by rbtcollins** [comment]
"Fix" - set 
```
        # enabled parallel loading and training on data (much faster)
        self.enable_async_loading = True
```
to False
